<div class="container-xxl flex-grow-1 container-p-y">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><div class="text-muted small">Contract #{{ $contract->id }}</div><h4 class="mb-0">Extend Contract</h4></div><a class="btn btn-outline-secondary" href="{{ route('rental-requests.details', $contract->id) }}">Back to contract</a></div>
    @if(session('message'))<div class="alert alert-success">{{ session('message') }}</div>@endif
    <div class="card mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><small class="text-muted">Original return</small><div>{{ $contract->original_return_date?->format('Y-m-d H:i') ?? $contract->return_date?->format('Y-m-d H:i') }}</div></div><div class="col-md-4"><small class="text-muted">Current planned return</small><div class="fw-semibold">{{ $contract->return_date?->format('Y-m-d H:i') }}</div></div><div class="col-md-4"><small class="text-muted">Actual return</small><div>{{ $contract->actual_return_at?->format('Y-m-d H:i') ?? 'Not returned' }}</div></div></div></div></div>
    @error('contract')<div class="alert alert-danger">{{ $message }}</div>@enderror
    @error('amendment')<div class="alert alert-danger">{{ $message }}</div>@enderror
    @if($this->canRequestExtension())
        <div class="card mb-4"><div class="card-body"><h5>New extension request</h5><form wire:submit="request" class="row g-3"><div class="col-md-4"><label class="form-label">New planned return</label><input wire:model="newReturnAt" type="datetime-local" class="form-control">@error('newReturnAt')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="col-md-3"><label class="form-label">Billing policy</label><select wire:model="pricingPolicy" class="form-select"><option value="daily_ceiling">Daily ceiling</option><option value="hourly">Hourly</option><option value="prorated_daily">Prorated daily</option><option value="grace_then_daily">Grace then daily</option></select></div><div class="col-md-5"><label class="form-label">Reason</label><input wire:model="reason" class="form-control"></div><div class="col-12"><label class="form-label">Notes</label><textarea wire:model="notes" class="form-control"></textarea></div><div class="col-12 d-flex gap-2"><button type="button" wire:click="preview" wire:loading.attr="disabled" class="btn btn-outline-primary">Preview price</button><button wire:loading.attr="disabled" class="btn btn-primary">Request extension</button></div></form>@if($quote !== [])<div class="alert alert-info mt-3 mb-0"><strong>Current quote: {{ number_format((float)$quote['total'], 2) }} {{ $quote['currency'] }}</strong><div class="small">Subtotal {{ number_format((float)$quote['subtotal'], 2) }} + VAT {{ number_format((float)$quote['tax'], 2) }}</div></div>@endif</div></div>
    @elseif(!in_array($contract->current_status, \App\Models\Contract::AMENDABLE_STATUSES, true))
        <div class="alert alert-warning">Only a delivered rental that has not yet been returned can be extended.</div>
    @else
        <div class="alert alert-info">Resolve the pending extension before creating another request.</div>
    @endif
    <div class="card"><div class="card-body"><h5>Amendment history</h5><div class="table-responsive"><table class="table"><thead><tr><th>#</th><th>Period</th><th>Status</th><th>Added total</th><th>Action</th></tr></thead><tbody>@forelse($contract->amendments as $amendment)<tr><td>{{ $amendment->sequence_no }}</td><td>{{ $amendment->extension_start_at?->format('Y-m-d H:i') }} → {{ $amendment->extension_end_at?->format('Y-m-d H:i') }}</td><td>{{ \Illuminate\Support\Str::headline($amendment->status) }}</td><td>{{ number_format((float)$amendment->total_amount, 2) }} {{ $amendment->currency }}</td><td>@if($amendment->isPending())<div class="d-flex gap-1"><button wire:click="approve({{ $amendment->id }})" wire:loading.attr="disabled" class="btn btn-sm btn-success">Approve</button><button wire:click="reject({{ $amendment->id }})" wire:loading.attr="disabled" class="btn btn-sm btn-outline-danger">Reject</button><button wire:click="cancel({{ $amendment->id }})" wire:loading.attr="disabled" class="btn btn-sm btn-outline-secondary">Cancel</button></div>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted">No amendments yet.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
