<?php

return [
    'sales_agents' => [
        'Website',
        'Alireza bakhshi',
        'Mohammadreza bakhshi',
        'TACI',
        'Foad sharifian',
        'Shahrokh gasht',
        'Zaman parvaz',
        'Hotel review global',
        'Dubai discount',
        'Mrs Saei',
        'Dubai offer',
        'Mr Navid',
        'Mrs khorrami',
        'Mr soleimani',
        'Mrs shams',
        'Mrs hashempour',
        'Sepris',
        'Sepid ball',
        'Javed',
        'Arkarsh',
        'Aftab Talayi',
        'Sahar Ravi',
        'Elahe Dezfuli',
        'Omid mardan',
        'Ahmad',
        'Iman Hoseini',
        'Respina',
        'Nil Seir Royaei',
        'Medisa',
    ],
];
