<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    use HasFactory;

    public const SALIK_AUTO_OTHER_REVENUE_PREFIX = 'Auto other revenue for Salik payment #';

    public const SALIK_TRIP_PAYMENT_TYPES = [
        'salik_4_aed' => 4.0,
        'salik_4_20_aed' => 4.2,
        'salik_6_aed' => 6.0,
        'salik_6_30_aed' => 6.3,
    ];

    public const SALIK_BREAKDOWN_TYPES = [
        'salik_4_aed',
        'salik_4_20_aed',
        'salik_6_aed',
        'salik_6_30_aed',
        'salik_other_revenue',
    ];

    public const PAYMENT_TYPE_LABELS = [
        'rental_fee' => 'Rental Fee',
        'security_deposit' => 'Security Deposit',
        'salik' => 'Salik (Legacy)',
        'salik_4_aed' => 'Salik (4 AED)',
        'salik_4_20_aed' => 'Salik (4.20 AED)',
        'salik_6_aed' => 'Salik (6 AED)',
        'salik_6_30_aed' => 'Salik (6.30 AED)',
        'salik_other_revenue' => 'Salik Other Revenue (Auto)',
        'fine' => 'Fine',
        'parking' => 'Parking',
        'damage' => 'Damage',
        'discount' => 'Discount',
        'payment_back' => 'Payment Back',
        'carwash' => 'Carwash',
        'fuel' => 'Fuel',
        'no_deposit_fee' => 'No Deposit Fee',
    ];

    protected $fillable = [
        'contract_id',
        'customer_id',
        'user_id',
        'car_id',
        'amount',
        'payment_method',
        'currency',
        'amount_in_aed',
        'payment_type',
        'description',
        'note',
        'payment_date',
        'is_refundable',
        'is_paid',
        'rate',
        'receipt',
        'security_deposit_image',
        'approval_status',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'amount_in_aed' => 'decimal:2',
        'payment_date' => 'date',
        'is_refundable' => 'boolean',
        'is_paid' => 'boolean',
        'approval_status' => 'string',
    ];

    public static function paymentTypes(): array
    {
        return array_keys(self::PAYMENT_TYPE_LABELS);
    }

    public static function paymentTypeLabels(): array
    {
        return self::PAYMENT_TYPE_LABELS;
    }

    public static function salikTripPaymentTypes(): array
    {
        return self::SALIK_TRIP_PAYMENT_TYPES;
    }

    public static function salikTripPaymentTypeKeys(): array
    {
        return array_keys(self::SALIK_TRIP_PAYMENT_TYPES);
    }

    public static function salikChargeTypes(): array
    {
        return ['salik', ...self::SALIK_BREAKDOWN_TYPES];
    }

    public static function isTripBasedSalikType(?string $paymentType): bool
    {
        return is_string($paymentType) && array_key_exists($paymentType, self::SALIK_TRIP_PAYMENT_TYPES);
    }

    public function isSalikBreakdownEntry(): bool
    {
        return in_array($this->payment_type, self::SALIK_BREAKDOWN_TYPES, true);
    }

    public function salikUnitAmount(): float
    {
        if ($this->payment_type === 'salik_other_revenue') {
            return 1.0;
        }

        return self::SALIK_TRIP_PAYMENT_TYPES[$this->payment_type] ?? 0.0;
    }

    public function salikTripCount(): int
    {
        if (! $this->isSalikBreakdownEntry()) {
            return 0;
        }

        $unit = $this->salikUnitAmount();

        if ($unit <= 0.0 || $this->amount_in_aed === null) {
            return 0;
        }

        return (int) round(((float) $this->amount_in_aed) / $unit);
    }

    public function salikBreakdownAmount(): float
    {
        if (! $this->isSalikBreakdownEntry()) {
            return 0.0;
        }

        return (float) $this->amount_in_aed;
    }

    public static function autoGeneratedOtherRevenueDescription(int $paymentId): string
    {
        return self::SALIK_AUTO_OTHER_REVENUE_PREFIX . $paymentId;
    }

    public function isAutoGeneratedSalikOtherRevenue(): bool
    {
        return $this->payment_type === 'salik_other_revenue'
            && is_string($this->description)
            && str_starts_with($this->description, self::SALIK_AUTO_OTHER_REVENUE_PREFIX);
    }

    public function syncAutoGeneratedOtherRevenue(int $tripCount): void
    {
        $description = self::autoGeneratedOtherRevenueDescription($this->id);

        if ($tripCount <= 0) {
            $this->deleteAutoGeneratedOtherRevenue();

            return;
        }

        if (! self::isTripBasedSalikType($this->payment_type)) {
            return;
        }

        $paymentDate = $this->payment_date;

        if ($paymentDate instanceof \DateTimeInterface) {
            $paymentDate = $paymentDate->format('Y-m-d');
        }

        $amount = round($tripCount, 2);

        self::updateOrCreate(
            [
                'payment_type' => 'salik_other_revenue',
                'contract_id' => $this->contract_id,
                'customer_id' => $this->customer_id,
                'description' => $description,
            ],
            [
                'user_id' => $this->user_id,
                'amount' => $amount,
                'currency' => 'AED',
                'amount_in_aed' => $amount,
                'payment_method' => $this->payment_method,
                'payment_date' => $paymentDate,
                'is_refundable' => false,
                'is_paid' => $this->is_paid,
                'rate' => null,
                'approval_status' => $this->approval_status,
            ]
        );
    }

    public function deleteAutoGeneratedOtherRevenue(): void
    {
        $description = self::autoGeneratedOtherRevenueDescription($this->id);

        self::where('payment_type', 'salik_other_revenue')
            ->where('contract_id', $this->contract_id)
            ->where('customer_id', $this->customer_id)
            ->where('description', $description)
            ->delete();
    }

    /**
     * دریافت پرداخت‌های انجام‌شده
     */
    public static function getPaidPayments()
    {
        return self::where('is_paid', true)->get();
    }

    /**
     * دریافت پرداخت‌های معوقه
     */
    public static function getUnpaidPayments()
    {
        return self::where('is_paid', false)->get();
    }

    /**
     * دریافت پرداخت‌های قابل استرداد
     */
    public static function getRefundablePayments()
    {
        return self::where('is_refundable', true)->get();
    }

    /**
     * محاسبه کل پرداخت‌های یک قرارداد خاص
     */
    public static function getTotalPaymentsForContract($contractId)
    {
        return self::where('contract_id', $contractId)->sum('amount');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }


    /**
     * محاسبه کل مبلغ پرداخت‌شده توسط یک مشتری
     */
    public static function getTotalPaymentsForCustomer($customerId)
    {
        return self::where('customer_id', $customerId)->sum('amount');
    }

    /**
     * ارتباط با قرارداد
     */
    public function contract()
    {
        return $this->belongsTo(Contract::class);
    }

    /**
     * ارتباط با مشتری
     */
    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    /**
     * ارتباط با خودرو
     */
    public function car()
    {
        return $this->belongsTo(Car::class);
    }
}
