<?php

namespace App\Livewire\Pages\Panel\Expert\Payments;

use App\Models\Payment;
use App\Models\Contract;
use App\Services\Media\DeferredImageUploadService;
use App\Livewire\Concerns\InteractsWithToasts;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithFileUploads;
use Carbon\Carbon;

class PaymentEdit extends Component
{
    use WithFileUploads;
    use InteractsWithToasts;

    public Payment $payment;
    public $paymentId;
    public $contractId;

    public $amount;
    public $currency = 'AED';
    public $rate;
    public $payment_type;
    public $payment_method = 'cash';
    public $payment_date;
    public $is_refundable = false;
    public $receipt;
    public $existingReceipt;
    public $note;
    public $salik_trip_count = '';
    public $salik_other_revenue_preview = 0;

    protected DeferredImageUploadService $deferredUploader;
    protected int $currentSalikTripCount = 0;

    public function boot(DeferredImageUploadService $deferredUploader): void
    {
        $this->deferredUploader = $deferredUploader;
    }

    private const PAYMENT_TYPES = [
        'rental_fee',
        'security_deposit',
        'salik',
        'salik_4_aed',
        'salik_6_aed',
        'salik_other_revenue',
        'fine',
        'parking',
        'damage',
        'discount',
        'payment_back',
        'carwash',
        'fuel',
        'no_deposit_fee',
    ];

    protected function rules(): array
    {
        $types = implode(',', self::PAYMENT_TYPES);

        return [
            'amount' => [
                'nullable',
                'numeric',
                'min:0',
                Rule::requiredIf(fn () => $this->payment_type !== null
                    && $this->payment_type !== ''
                    && ! in_array($this->payment_type, ['salik', 'salik_4_aed', 'salik_6_aed'], true)),
            ],
            'currency' => 'required|in:IRR,USD,AED,EUR,SAR,OMR',
            'payment_type' => 'required|in:' . $types,
            'payment_method' => 'required|in:cash,transfer,ticket',
            'payment_date' => 'required|date',
            'is_refundable' => 'required|boolean',
            'rate' => 'nullable|numeric|min:0.0001',
            'receipt' => 'nullable|image|mimes:jpg,jpeg,png,webp|max:8048',
            'note' => 'nullable|string|max:2000',
            'salik_trip_count' => ['required_if:payment_type,salik_4_aed,salik_6_aed', 'integer', 'min:0'],
        ];
    }

    public function mount($paymentId)
    {
        $this->paymentId = $paymentId;
        $this->payment = Payment::with('contract')->findOrFail($paymentId);

        $this->authorizeUser();

        $this->contractId = $this->payment->contract_id;
        $this->amount = $this->payment->amount;
        $this->currency = $this->payment->currency;
        $this->rate = $this->payment->rate;
        $this->payment_type = $this->payment->payment_type;
        $this->payment_method = $this->payment->payment_method;
        $this->payment_date = $this->payment->payment_date?->format('Y-m-d') ?? now()->format('Y-m-d');
        $this->is_refundable = (bool) $this->payment->is_refundable;
        $this->existingReceipt = $this->payment->receipt;
        $this->note = $this->payment->note;
        $this->salik_trip_count = $this->resolveInitialSalikTrips();
        $this->refreshSalikDerivedFields();
    }

    private function authorizeUser(): void
    {
        if (!Auth::check()) {
            abort(403);
        }

        // if ($this->payment->contract && $this->payment->contract->user_id && $this->payment->contract->user_id !== Auth::id()) {
        //     abort(403, 'You are not allowed to edit this payment.');
        // }
    }

    public function updatedCurrency(string $value): void
    {
        if ($value === 'AED') {
            $this->rate = null;
        }
    }

    public function getPaymentTypeOptionsProperty(): array
    {
        return [
            'rental_fee' => 'Rental Fee',
            'security_deposit' => 'Security Deposit',
            'salik' => 'Salik (Legacy)',
            'salik_4_aed' => 'Salik (4 AED)',
            'salik_6_aed' => 'Salik (6 AED)',
            'salik_other_revenue' => 'Salik Other Revenue (Auto)',
            'fine' => 'Fine',
            'parking' => 'Parking',
            'damage' => 'Damage',
            'discount' => 'Discount',
            'payment_back' => 'Payment Back',
            'carwash' => 'Carwash',
            'fuel' => 'Fuel',
            'no_deposit_fee' => 'No Deposit Fee',
        ];
    }

    public function updatePayment()
    {
        if ($this->payment->isAutoGeneratedSalikOtherRevenue()) {
            $this->toast('error', 'Auto-generated other revenue entries are managed automatically.');

            return redirect()->route('rental-requests.payment', [$this->payment->contract_id, $this->payment->customer_id]);
        }

        if (in_array($this->payment_type, ['salik', 'salik_4_aed', 'salik_6_aed'], true) && $this->amount === '') {
            $this->amount = 0;
        } elseif ($this->amount === '') {
            $this->amount = null;
        }

        $this->validate();

        if ($this->currency !== 'AED' && empty($this->rate)) {
            $this->addError('rate', 'Exchange rate is required for non-AED currencies.');
            return;
        }

        if (in_array($this->payment_type, ['fine', 'parking', 'damage']) && !$this->existingReceipt && !$this->receipt) {
            $this->addError('receipt', 'Receipt is required for fines, parking, or damage charges.');
            return;
        }

        $salikTrips = 0;

        if (in_array($this->payment_type, ['salik', 'salik_4_aed', 'salik_6_aed'], true)) {
            $aedAmount = $this->resolveSalikAmount();
            $this->amount = $aedAmount;
            $this->currency = 'AED';
            $this->rate = null;
            $salikTrips = $this->currentSalikTripCount;
        } else {
            $aedAmount = match ($this->currency) {
                'AED' => $this->amount,
                'IRR' => round($this->amount / $this->rate, 2),
                default => round($this->amount * $this->rate, 2),
            };
        }

        $receiptPath = $this->existingReceipt;

        if ($this->receipt) {
            if ($this->existingReceipt && Storage::disk('myimage')->exists($this->existingReceipt)) {
                Storage::disk('myimage')->delete($this->existingReceipt);
            }

            $baseName = "payment_receipt_{$this->payment->contract_id}_" . time();
            $receiptPath = $this->deferredUploader->store(
                $this->receipt,
                "payment_receipts/{$baseName}.webp",
                'myimage',
                ['quality' => 30, 'max_width' => 1600, 'max_height' => 1600]
            );
        }

        $originalType = $this->payment->payment_type;

        DB::transaction(function () use ($aedAmount, $receiptPath, $salikTrips, $originalType) {
            $this->payment->update([
                'amount' => $this->amount,
                'currency' => $this->currency,
                'rate' => $this->currency !== 'AED' ? $this->rate : null,
                'amount_in_aed' => $aedAmount,
                'payment_type' => $this->payment_type,
                'payment_method' => $this->payment_method,
                'payment_date' => Carbon::parse($this->payment_date)->format('Y-m-d'),
                'is_refundable' => $this->is_refundable,
                'receipt' => $receiptPath,
                'note' => $this->note,
            ]);

            if (in_array($this->payment_type, ['salik_4_aed', 'salik_6_aed'], true)) {
                $this->payment->refresh();
                $this->payment->syncAutoGeneratedOtherRevenue($salikTrips);
            } elseif (in_array($originalType, ['salik_4_aed', 'salik_6_aed'], true)) {
                $this->payment->refresh();
                $this->payment->deleteAutoGeneratedOtherRevenue();
            }
        });

        $this->toast('success', 'Payment updated successfully.');

        return redirect()->route('rental-requests.payment', [$this->payment->contract_id, $this->payment->customer_id]);
    }

    public function updatedPaymentType($value): void
    {
        if (blank($value)) {
            $this->amount = null;
            $this->salik_trip_count = '';
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;
        }

        if (in_array($value, ['salik', 'salik_4_aed', 'salik_6_aed'], true)) {
            $this->currency = 'AED';
            $this->rate = null;

            if ($value !== 'salik') {
                $this->salik_trip_count = '';
            }
        } elseif (! blank($value)) {
            $this->salik_trip_count = '';
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;
        }

        $this->refreshSalikDerivedFields();
    }

    public function updatedSalikTripCount($value): void
    {
        $this->refreshSalikDerivedFields();
    }

    private function resolveSalikAmount(): float
    {
        if ($this->payment_type === 'salik') {
            $this->currentSalikTripCount = 0;
            return (float) $this->amount;
        }

        $trips = $this->getSanitizedSalikTripCount();
        $this->currentSalikTripCount = $trips;

        if ($trips < 0) {
            throw ValidationException::withMessages([
                'salik_trip_count' => 'Trip count cannot be negative.',
            ]);
        }

        $unit = match ($this->payment_type) {
            'salik_4_aed' => 4,
            'salik_6_aed' => 6,
            default => 0,
        };

        return $trips * $unit;
    }

    private function resolveInitialSalikTrips(): string
    {
        if (! in_array($this->payment->payment_type, ['salik_4_aed', 'salik_6_aed', 'salik_other_revenue'], true)) {
            return '';
        }

        $unit = match ($this->payment->payment_type) {
            'salik_4_aed' => 4,
            'salik_6_aed' => 6,
            'salik_other_revenue' => 1,
            default => 0,
        };

        if ($unit <= 0) {
            return '';
        }

        return (string) (int) round(((float) $this->payment->amount_in_aed) / $unit);
    }

    public function render()
    {
        return view('livewire.pages.panel.expert.payments.payment-edit', [
            'payment' => $this->payment,
            'contract' => $this->payment->contract ?? Contract::find($this->contractId),
        ]);
    }

    private function refreshSalikDerivedFields(): void
    {
        if (! in_array($this->payment_type, ['salik_4_aed', 'salik_6_aed'], true)) {
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;

            return;
        }

        $trips = $this->getSanitizedSalikTripCount();
        $this->currentSalikTripCount = $trips;
        $this->salik_other_revenue_preview = $trips;

        $unit = $this->payment_type === 'salik_4_aed' ? 4 : 6;
        $this->amount = $trips * $unit;
    }

    private function getSanitizedSalikTripCount(): int
    {
        $trips = (int) ($this->salik_trip_count ?? 0);

        if ($trips < 0) {
            return 0;
        }

        return $trips;
    }
}
