<?php

namespace App\Livewire\Pages\Panel\Expert\Payments;

use App\Models\Payment;
use App\Models\Contract;
use App\Services\Media\DeferredImageUploadService;
use App\Livewire\Concerns\LogsBusinessRead;
use App\Livewire\Concerns\InteractsWithToasts;
use App\Livewire\Concerns\RefreshesFileInputs;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Livewire\Component;
use Livewire\WithFileUploads;
use Carbon\Carbon;

class PaymentEdit extends Component
{
    use WithFileUploads;
    use InteractsWithToasts;
    use RefreshesFileInputs;
    use LogsBusinessRead;

    public Payment $payment;
    public $paymentId;
    public $contractId;

    public $amount;
    public $currency = 'AED';
    public $rate;
    public $payment_type;
    public $payment_method = 'cash';
    public $payment_date;
    public $is_refundable = false;
    public $receipt;
    public array $damageReceipts = [];
    public $existingReceipt;
    public array $existingDamageImages = [];
    public $note;
    public $salik_trip_count = '';
    public $salik_other_revenue_preview = 0;

    protected DeferredImageUploadService $deferredUploader;
    protected int $currentSalikTripCount = 0;

    public function boot(DeferredImageUploadService $deferredUploader): void
    {
        $this->deferredUploader = $deferredUploader;
    }

    protected function rules(): array
    {
        $types = implode(',', Payment::paymentTypes());
        $manualAmountSalikTypes = array_merge(['salik'], Payment::salikTripPaymentTypeKeys());

        return [
            'amount' => [
                'nullable',
                'numeric',
                'min:0',
                Rule::requiredIf(fn () => $this->payment_type !== null
                    && $this->payment_type !== ''
                    && ! in_array($this->payment_type, $manualAmountSalikTypes, true)),
            ],
            'currency' => 'required|in:IRR,USD,AED,EUR,SAR,OMR',
            'payment_type' => 'required|in:' . $types,
            'payment_method' => 'required|in:cash,transfer,ticket',
            'payment_date' => 'required|date',
            'is_refundable' => 'required|boolean',
            'rate' => 'nullable|numeric|min:0.0001',
            'receipt' => 'nullable|image|mimes:jpg,jpeg,png,webp|max:8048',
            'damageReceipts' => 'nullable|array|max:5',
            'damageReceipts.*' => 'image|mimes:jpg,jpeg,png,webp|max:8048',
            'note' => 'nullable|string|max:2000',
            'salik_trip_count' => ['required_if:payment_type,' . implode(',', Payment::salikTripPaymentTypeKeys()), 'integer', 'min:0'],
        ];
    }

    public function mount($paymentId)
    {
        $this->paymentId = $paymentId;
        $this->payment = Payment::with('contract')->findOrFail($paymentId);

        $this->authorizeUser();

        $this->contractId = $this->payment->contract_id;
        $this->amount = $this->payment->amount;
        $this->currency = $this->payment->currency;
        $this->rate = $this->payment->rate;
        $this->payment_type = $this->payment->payment_type;
        $this->payment_method = $this->payment->payment_method;
        $this->payment_date = $this->payment->payment_date?->format('Y-m-d') ?? now()->format('Y-m-d');
        $this->is_refundable = (bool) $this->payment->is_refundable;
        $this->existingReceipt = $this->payment->receipt;
        $this->existingDamageImages = $this->payment->damageImagePaths();
        $this->note = $this->payment->note;
        $this->salik_trip_count = $this->resolveInitialSalikTrips();
        $this->refreshSalikDerivedFields();
        $this->auditBusinessRead([
            'payment_id' => $this->payment->id,
            'contract_id' => $this->payment->contract_id,
            'customer_id' => $this->payment->customer_id,
        ]);
    }

    private function authorizeUser(): void
    {
        if (!Auth::check()) {
            abort(403);
        }

        // if ($this->payment->contract && $this->payment->contract->user_id && $this->payment->contract->user_id !== Auth::id()) {
        //     abort(403, 'You are not allowed to edit this payment.');
        // }
    }

    public function updatedCurrency(string $value): void
    {
        if ($value === 'AED') {
            $this->rate = null;
        }
    }

    public function getPaymentTypeOptionsProperty(): array
    {
        return Payment::paymentTypeLabels();
    }

    public function updatePayment()
    {
        if ($this->payment->isAutoGeneratedSalikOtherRevenue()) {
            $this->toast('error', 'Auto-generated other revenue entries are managed automatically.');

            return redirect()->route('rental-requests.payment', [$this->payment->contract_id, $this->payment->customer_id]);
        }

        if (in_array($this->payment_type, array_merge(['salik'], Payment::salikTripPaymentTypeKeys()), true) && $this->amount === '') {
            $this->amount = 0;
        } elseif ($this->amount === '') {
            $this->amount = null;
        }

        $this->validate();

        if ($this->currency !== 'AED' && empty($this->rate)) {
            $this->addError('rate', 'Exchange rate is required for non-AED currencies.');
            return;
        }

        if (in_array($this->payment_type, ['fine', 'parking'], true) && !$this->existingReceipt && !$this->receipt) {
            $this->addError('receipt', 'Receipt is required for fines and parking charges.');
            return;
        }

        $salikTrips = 0;

        if (in_array($this->payment_type, array_merge(['salik'], Payment::salikTripPaymentTypeKeys()), true)) {
            $aedAmount = $this->resolveSalikAmount();
            $this->amount = $aedAmount;
            $this->currency = 'AED';
            $this->rate = null;
            $salikTrips = $this->currentSalikTripCount;
        } else {
            $aedAmount = match ($this->currency) {
                'AED' => $this->amount,
                'IRR' => round($this->amount / $this->rate, 2),
                default => round($this->amount * $this->rate, 2),
            };
        }

        $receiptPath = $this->existingReceipt;
        $oldReceiptPath = $this->existingReceipt;
        $existingDamagePaths = $this->existingDamageImages;
        $damageImagePaths = $existingDamagePaths;
        $uploadedPaths = [];
        $pathsToDeleteAfterSave = [];

        $originalType = $this->payment->payment_type;

        try {
            if ($this->payment_type === 'damage') {
                if ($this->normalizedDamageReceipts() !== []) {
                    $damageImagePaths = [];

                    foreach ($this->normalizedDamageReceipts() as $index => $damageReceipt) {
                        $storedPath = $this->storePaymentImage($damageReceipt, 'damage-' . ($index + 1));
                        $damageImagePaths[] = $storedPath;
                        $uploadedPaths[] = $storedPath;
                    }

                    $pathsToDeleteAfterSave = array_values(array_unique(array_filter([
                        ...$existingDamagePaths,
                        $oldReceiptPath,
                    ])));
                }

                $receiptPath = $damageImagePaths[0] ?? null;
            } elseif ($this->receipt) {
                $receiptPath = $this->storePaymentImage($this->receipt, 'receipt');
                $uploadedPaths[] = $receiptPath;
                $pathsToDeleteAfterSave = array_values(array_unique(array_filter([
                    ...$existingDamagePaths,
                    $oldReceiptPath,
                ])));
            } elseif ($originalType === 'damage') {
                $pathsToDeleteAfterSave = array_values(array_unique(array_filter(array_slice($existingDamagePaths, 1))));
                $receiptPath = $oldReceiptPath;
            }

            if ($this->payment_type !== 'damage') {
                $damageImagePaths = [];
            }

            DB::transaction(function () use ($aedAmount, $receiptPath, $damageImagePaths, $salikTrips, $originalType) {
                $this->payment->update([
                    'amount' => $this->amount,
                    'currency' => $this->currency,
                    'rate' => $this->currency !== 'AED' ? $this->rate : null,
                    'amount_in_aed' => $aedAmount,
                    'payment_type' => $this->payment_type,
                    'payment_method' => $this->payment_method,
                    'payment_date' => Carbon::parse($this->payment_date)->format('Y-m-d'),
                    'is_refundable' => $this->is_refundable,
                    'receipt' => $receiptPath,
                    'damage_images' => $damageImagePaths !== [] ? $damageImagePaths : null,
                    'note' => $this->note,
                ]);

                if (Payment::isTripBasedSalikType($this->payment_type)) {
                    $this->payment->refresh();
                    $this->payment->syncAutoGeneratedOtherRevenue($salikTrips);
                } elseif (Payment::isTripBasedSalikType($originalType)) {
                    $this->payment->refresh();
                    $this->payment->deleteAutoGeneratedOtherRevenue();
                }
            });
        } catch (\Throwable $exception) {
            $this->deleteStoredPaths($uploadedPaths);

            $this->toast('error', 'Payment update failed: ' . $exception->getMessage(), false);

            return;
        }

        $this->deleteStoredPaths(array_diff($pathsToDeleteAfterSave, array_filter([$receiptPath])));

        $this->existingReceipt = $receiptPath;
        $this->existingDamageImages = $this->payment_type === 'damage'
            ? ($damageImagePaths !== [] ? $damageImagePaths : array_filter([$receiptPath]))
            : [];
        $this->receipt = null;
        $this->damageReceipts = [];
        $this->refreshFileInputs();

        $this->toast('success', 'Payment updated successfully.');

        return redirect()->route('rental-requests.payment', [$this->payment->contract_id, $this->payment->customer_id]);
    }

    public function updatedPaymentType($value): void
    {
        if (blank($value)) {
            $this->amount = null;
            $this->salik_trip_count = '';
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;
        }

        if (in_array($value, array_merge(['salik'], Payment::salikTripPaymentTypeKeys()), true)) {
            $this->currency = 'AED';
            $this->rate = null;

            if ($value !== 'salik') {
                $this->salik_trip_count = '';
            }
        } elseif (! blank($value)) {
            $this->salik_trip_count = '';
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;
        }

        $shouldRefreshFileInputs = false;

        if ($value !== 'damage' && $this->damageReceipts !== []) {
            $this->damageReceipts = [];
            $shouldRefreshFileInputs = true;
        }

        if ($value === 'damage' && $this->receipt) {
            $this->receipt = null;
            $shouldRefreshFileInputs = true;
        }

        if ($shouldRefreshFileInputs) {
            $this->refreshFileInputs();
        }

        $this->refreshSalikDerivedFields();
    }

    public function updatedSalikTripCount($value): void
    {
        $this->refreshSalikDerivedFields();
    }

    private function resolveSalikAmount(): float
    {
        if ($this->payment_type === 'salik') {
            $this->currentSalikTripCount = 0;
            return (float) $this->amount;
        }

        $trips = $this->getSanitizedSalikTripCount();
        $this->currentSalikTripCount = $trips;

        if ($trips < 0) {
            throw ValidationException::withMessages([
                'salik_trip_count' => 'Trip count cannot be negative.',
            ]);
        }

        $unit = Payment::salikTripPaymentTypes()[$this->payment_type] ?? 0;

        return $trips * $unit;
    }

    private function resolveInitialSalikTrips(): string
    {
        if (! in_array($this->payment->payment_type, [...Payment::salikTripPaymentTypeKeys(), 'salik_other_revenue'], true)) {
            return '';
        }

        $unit = $this->payment->payment_type === 'salik_other_revenue'
            ? 1
            : (Payment::salikTripPaymentTypes()[$this->payment->payment_type] ?? 0);

        if ($unit <= 0) {
            return '';
        }

        return (string) (int) round(((float) $this->payment->amount_in_aed) / $unit);
    }

    public function render()
    {
        return view('livewire.pages.panel.expert.payments.payment-edit', [
            'payment' => $this->payment,
            'contract' => $this->payment->contract ?? Contract::find($this->contractId),
        ]);
    }

    private function refreshSalikDerivedFields(): void
    {
        if (! Payment::isTripBasedSalikType($this->payment_type)) {
            $this->salik_other_revenue_preview = 0;
            $this->currentSalikTripCount = 0;

            return;
        }

        $trips = $this->getSanitizedSalikTripCount();
        $this->currentSalikTripCount = $trips;
        $this->salik_other_revenue_preview = $trips;

        $unit = Payment::salikTripPaymentTypes()[$this->payment_type] ?? 0;
        $this->amount = $trips * $unit;
    }

    private function getSanitizedSalikTripCount(): int
    {
        $trips = (int) ($this->salik_trip_count ?? 0);

        if ($trips < 0) {
            return 0;
        }

        return $trips;
    }

    private function normalizedDamageReceipts(): array
    {
        return array_values(array_filter(
            $this->damageReceipts,
            fn ($receipt) => $receipt !== null
        ));
    }

    private function storePaymentImage($file, string $suffix): string
    {
        return $this->deferredUploader->store(
            $file,
            'payment_receipts/payment-' . $this->payment->contract_id . '-' . $suffix . '-' . Str::uuid() . '.webp',
            'myimage',
            ['quality' => 30, 'max_width' => 1600, 'max_height' => 1600]
        );
    }

    private function deleteStoredPaths(array $paths): void
    {
        foreach (array_unique(array_filter($paths)) as $path) {
            if (Storage::disk('myimage')->exists($path)) {
                Storage::disk('myimage')->delete($path);
            }
        }
    }
}
